import Navbar from "@/components/Navbar"
import Provider from "@/components/Provider"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <Provider>
          <Navbar />
      <main>{children}</main>
      </Provider>
      </body>
    </html>
  )
}
